# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$time"""

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user](bold blue) on [$hostname](italic dimmed white)"
disabled = false
show_always = true

[directory]
truncation_length = 3
truncation_symbol = "…/"

[fill]
symbol = ' '
style = 'bold green'

[hostname]
ssh_only = false
format =  "  "
trim_at = ".companyname.com"
disabled = false

[status]
style = "bg:blue"
symbol = " "
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[time]
disabled = false
format = '[ $time  ]($style) '
time_format = "%T"
utc_time_offset = "+8"

[c]
# [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ] ]
commands = [['','']]

[conda]
format = 'via [$symbol$environment](green) '
ignore_base = false

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
